# Generated by Django 5.0.4 on 2024-04-23 21:00

from django.db import migrations

def populate_table_categoria(apps, schema_editor):
    Categoria = apps.get_model('pets', 'Categoria')
    Categoria.objects.bulk_create([
        Categoria(nome = 'Cachorro'),
        Categoria(nome = 'Gato'),
        Categoria(nome = 'Ave'),
        Categoria(nome = 'Roedor'),
        Categoria(nome = 'Peixe'),
    ])

def populate_table_porte(apps, schema_editor):
    Porte = apps.get_model('pets', 'Porte')
    Porte.objects.bulk_create([
        Porte(descricao = 'Mini', peso_min = 0, peso_max = 5),
        Porte(descricao = 'Pequeno', peso_min = 6, peso_max = 14),
        Porte(descricao = 'Médio', peso_min = 15, peso_max = 24),
        Porte(descricao = 'Grande', peso_min = 25, peso_max = 44),
        Porte(descricao = 'Enorme', peso_min = 45, peso_max = 100),
    ])

class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_table_categoria),
        migrations.RunPython(populate_table_porte),
    ]
