# Generated by Django 5.0.4 on 2024-11-02 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoas', '0002_alter_cliente_options_alter_funcionario_options_and_more'),
        ('pets', '0002_auto_20240423_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('H', 'Hospedagem'), ('P', 'Passeio'), ('V', 'Visita')], max_length=1, verbose_name='Tipo de Serviço')),
                ('status', models.CharField(choices=[('A', 'Agendado'), ('B', 'Em Andamento'), ('C', 'Concluído'), ('D', 'Cancelado')], default='A', max_length=1, verbose_name='Status do Serviço')),
                ('data_hora_criacao', models.DateTimeField(auto_now=True)),
                ('data_hora_inicio', models.DateTimeField()),
                ('data_hora_fim', models.DateField(blank=True, null=True)),
                ('funcionario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pessoas.funcionario')),
                ('pets', models.ManyToManyField(related_name='servicos', to='pets.pet', verbose_name='Pets')),
            ],
        ),
    ]
