services:

  api:
    container_name: pet-happy-api
    build:
      context: ..
      dockerfile: infra/Dockerfile
    restart: always
    command: > 
      sh -c "sleep 20 &&
              python manage.py migrate &&
              python manage.py createsuperuser --no-input &&
              python manage.py runserver 0.0.0.0:8000"
    env_file:
     - .env.dev
    ports:
      - 8000:8000
    networks:
      - backend-bridge
    depends_on:
      - db
     
  db:
    container_name: mysql-db
    image: mysql
    restart: always
    env_file:
      - .env.dev
    volumes:
      - ./base.sql:/docker-entrypoint-initdb.d/base.sql
    expose:
      - 3306
    networks:
      - backend-bridge

networks:
  backend-bridge:
    driver: bridge