services:

  api:
    container_name: pet-happy-back
    build:
      context: ..
      dockerfile: infra/Dockerfile
    restart: always
    command: > 
      sh -c "sleep 5 &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:80"
    ports:
      - 80:80
    expose:
      - 80