# Generated by Django 5.0.4 on 2024-10-11 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['pessoa__nome']},
        ),
        migrations.AlterModelOptions(
            name='funcionario',
            options={'ordering': ['pessoa__nome']},
        ),
        migrations.AlterModelOptions(
            name='veterinario',
            options={'ordering': ['pessoa__nome']},
        ),
    ]
