# Generated by Django 5.0.4 on 2024-11-02 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_alter_cliente_options_alter_funcionario_options_and_more'),
        ('pets', '0003_remove_cuidadoespecial_pet_remove_medicamento_pet_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Veterinario',
        ),
    ]
